# Grid Size

CELL_SIZE = 30

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000

GRID_ROWS = SCREEN_HEIGHT // CELL_SIZE
GRID_COLUMNS = SCREEN_WIDTH // CELL_SIZE

ROW_MARGIN = (SCREEN_WIDTH - (CELL_SIZE * GRID_COLUMNS)) / 2
COLUMN_MARGIN = (SCREEN_HEIGHT - (CELL_SIZE * GRID_ROWS)) / 2


# Maze Size

MAZE_GRID_ROWS = 36
MAZE_GRID_COLUMNS = 28


# Maze starting position

ROW_MARGIN = (SCREEN_WIDTH - (CELL_SIZE * MAZE_GRID_COLUMNS)) /2
COLUMN_MARGIN = (SCREEN_HEIGHT - (CELL_SIZE * MAZE_GRID_ROWS)) /2

MAZE_LEVEL_START_X = (-SCREEN_WIDTH / 2) + ROW_MARGIN + (CELL_SIZE / 2)
MAZE_LEVEL_START_Y = (SCREEN_HEIGHT / 2) - COLUMN_MARGIN - (CELL_SIZE / 2)